service: user-service

provider:
 name: aws
 runtime: nodejs18.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: dev
 region: us-east-1 # AWS region

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /